using System;
using System.Threading;
using System.Threading.Tasks;
using Confluent.Kafka;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SentinelKafka.Messaging;

namespace SentinelKafka.Tests;

#if ENABLE_PROTOBUF_EXAMPLES

// 1. In reality, `MyProtobufOrder` applies to classes implicitly auto-generated by the protobuf (protoc) compiler natively integrated from your .proto file schemas!
// This example inherently relies on that generated partial class implementing standard Google.Protobuf.IMessage<T>.

public class SampleProtobufConsumer : ProtobufKafkaConsumerBase<MyProtobufOrder>
{
    // Define the alias mapping configured securely in appsettings.json for this environment
    protected override string TopicName => "OrdersTopicAlias";
    protected override string GroupIdName => "OrdersGroupAlias";

    public SampleProtobufConsumer(
        ILogger<SampleProtobufConsumer> logger,
        IOptions<KafkaOptions> kafkaConfig,
        IHostEnvironment env,
        IServiceScopeFactory scopeFactory) 
        : base(logger, kafkaConfig, env, scopeFactory)
    {
    }

    // 2. Process the heavily validated, statically-typed binary Protobuf payload directly!
    // If the schema contract strictly evaluated upon consumption mismatches structurally, this logic is safely bypassed, routing securely natively to your abstract DLQ architecture!
    protected override async Task ProcessMessageAsync(MyProtobufOrder message, CancellationToken ct)
    {
        _logger.LogInformation("Processing strictly-typed Binary Protobuf Order: {OrderId}", message.Id);
        
        await Task.Delay(500, ct);

        // Explicit exceptions are flawlessly routed to standard DLQ execution pipelines just identically to JSON implementations!
        if (message.Amount < 0)
        {
            throw new InvalidOperationException("Order amount cannot literally evaluate negatively!");
        }

        _logger.LogInformation("Successfully completed processing Protobuf Order {OrderId}", message.Id);
    }
}
#endif
